### ISSUE TITLE
Добавление функционала

### ISSUE THREAD

**Issue by Truyn** [deathscore13/plugins_chat_filter#1]
Работает интересно, все как надо.
Неплохо было бы модулем или доп функционалом чтобы проверяло еще 
Никнейм+клантег
Так же как понимаю хотя я и пишу слова г+а+н+д+о+н то если человек напишет с пробелами фильтр не сработает типо г а н д о н
Еще момент не понял как заблокировать не по https/http а по доменам первого уровня .ru .com .net и тд.
![image](https://user-images.githubusercontent.com/53527324/235351439-fda14b97-839a-4830-9258-02c69a706e62.png)
В этот синтаксис вообще не врубился как тут писать.

**Comment by deathscore13** [comment]
> Неплохо было бы модулем или доп функционалом чтобы проверяло еще
Никнейм+клантег

Такого не будет. Суть данного решения - блокировать вызов `OnClientSayCommand_Post` для плагинов работающих с ним. Я пытался найти что-то подобное, т.к. мне не хотелось добавлять фильтр в [source_connection](https://github.com/deathscore13/source_connection).

> Так же как понимаю хотя я и пишу слова г+а+н+д+о+н то если человек напишет с пробелами фильтр не сработает типо г а н д о н
Еще момент не понял как заблокировать не по https/http а по доменам первого уровня .ru .com .net и тд.
[image](https://user-images.githubusercontent.com/53527324/235351439-fda14b97-839a-4830-9258-02c69a706e62.png)
В этот синтаксис вообще не врубился как тут писать.

Плагин использует регулярные выражения. В настройках указаны только несколько скудных примеров. Некоторые из них были взяты [отсюда](https://github.com/FAQU2/Advanced-Filters/blob/main/addons/sourcemod/scripting/advanced-filters.sp#L24-L25). Вы можете научиться пользоваться регулярными выражениями с помощью [этого](https://regex101.com/) сайта.

**Comment by Truyn** [comment]
Чтобы понять как их использовать сначала надо это регулярное выражение разобрать а указанный сайт этого не делает

**Comment by deathscore13** [comment]
> Чтобы понять как их использовать сначала надо это регулярное выражение разобрать а указанный сайт этого не делает

Внезапно, делает. Там есть раздел где описывается каждый токен.
<details>
<summary>Спойлер</summary>

![Screenshot_20230502-220420](https://user-images.githubusercontent.com/109452726/235762860-e36717c5-5d69-4a5d-a9bc-976d0b867c07.jpg)
</details>
